name: Ingest Platzi Products

on:
  push:
    branches:
      - main

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -e .

      - name: Run ingestion script
        run: python src/main.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ingestion-artifacts
          path: src/static/